name: C++ Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile C++ Code
      run: g++ -std=c++17 -Wall -Wextra Bank-Management-System.cpp -o bank_app
